# Generated by Django 5.1 on 2026-06-20 11:30

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_code', models.CharField(help_text='Hoofdletters, bv. NL, DE (OpenHolidays countryIsoCode).', max_length=2, unique=True, verbose_name='ISO-landcode')),
                ('slug', models.SlugField(blank=True, max_length=80, unique=True, verbose_name='Slug')),
                ('naam', models.CharField(max_length=80, verbose_name='Naam')),
                ('vlag', models.CharField(blank=True, max_length=8, verbose_name='Vlag (emoji)')),
                ('intro', models.TextField(blank=True, verbose_name='Intro')),
                ('regio_info', models.TextField(blank=True, verbose_name='Regio-uitleg (algemeen)')),
                ('studiedagen_uitleg', models.TextField(blank=True, verbose_name='Studiedagen — uitleg')),
                ('weer_bron', models.CharField(blank=True, max_length=160, verbose_name='Weer — bron')),
                ('weer_beste', models.CharField(blank=True, max_length=255, verbose_name='Weer — beste periode')),
                ('bron', models.CharField(blank=True, max_length=300, verbose_name='Databron-vermelding')),
                ('bijgewerkt', models.CharField(blank=True, help_text="bijv. 'mei 2026'.", max_length=40, verbose_name='Bijgewerkt (weergave)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Volgorde')),
                ('actief', models.BooleanField(default=True, verbose_name='Actief')),
                ('imported_at', models.DateTimeField(blank=True, null=True, verbose_name='Laatst geïmporteerd')),
            ],
            options={
                'verbose_name': 'Land',
                'verbose_name_plural': 'Landen',
                'ordering': ['order', 'naam'],
            },
        ),
        migrations.AddField(
            model_name='expert',
            name='credentials',
            field=models.TextField(blank=True, help_text="Eén per regel, bijv. '14 jaar reisredactie'.", verbose_name='Credentials'),
        ),
        migrations.AddField(
            model_name='expert',
            name='kort',
            field=models.CharField(blank=True, help_text="bijv. 'Hoofdredacteur' (compacte weergave).", max_length=60, verbose_name='Korte functie'),
        ),
        migrations.AddField(
            model_name='expert',
            name='mono',
            field=models.CharField(blank=True, help_text="Mono-label, bijv. 'SdV'.", max_length=6, verbose_name='Initialen'),
        ),
        migrations.AddField(
            model_name='expert',
            name='sinds',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Werkzaam sinds (jaar)'),
        ),
        migrations.AlterField(
            model_name='expert',
            name='tags',
            field=models.CharField(blank=True, help_text="Komma-gescheiden, bijv. 'Redactie, Slim plannen'.", max_length=255, verbose_name='Focus / tags'),
        ),
        migrations.CreateModel(
            name='Bestemming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_upload', models.ImageField(blank=True, null=True, upload_to=core.models._photo_upload_to, verbose_name='Foto uploaden')),
                ('photo_url', models.URLField(blank=True, max_length=500, verbose_name='Foto URL (extern)')),
                ('photo_local', models.CharField(blank=True, help_text='Wordt automatisch ingevuld door de Pexels-widget.', max_length=300, verbose_name='Foto lokaal pad')),
                ('photo_credit', models.CharField(blank=True, max_length=200, verbose_name='Fotocredit')),
                ('photo_pexels_id', models.CharField(blank=True, max_length=20, verbose_name='Pexels foto-ID')),
                ('photo_alt', models.CharField(blank=True, help_text='Beschrijf de foto voor SEO en screenreaders.', max_length=300, verbose_name='Alt-tekst')),
                ('naam', models.CharField(max_length=120, verbose_name='Naam')),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True, verbose_name='Slug')),
                ('land_naam', models.CharField(blank=True, help_text="Vrije tekst, bv. 'Portugal' als er geen landpagina is.", max_length=80, verbose_name='Land (weergave)')),
                ('slim_score', models.PositiveSmallIntegerField(default=0, verbose_name='Slim-score (0–100)')),
                ('gezin_score', models.PositiveSmallIntegerField(default=0, verbose_name='Gezinsscore (0–100)')),
                ('tag', models.CharField(blank=True, help_text="bijv. 'Rustig in september'.", max_length=60, verbose_name='Tag')),
                ('beste_week', models.CharField(blank=True, help_text="bijv. 'wk 37 · 7 sep'.", max_length=40, verbose_name='Beste week')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Volgorde')),
                ('actief', models.BooleanField(default=True, verbose_name='Actief')),
                ('land', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bestemmingen', to='core.land', verbose_name='Land (gekoppeld)')),
            ],
            options={
                'verbose_name': 'Bestemming',
                'verbose_name_plural': 'Bestemmingen',
                'ordering': ['order', 'naam'],
            },
        ),
        migrations.CreateModel(
            name='Regio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='OpenHolidays-code, bv. DE-BY of NL-NoordNederland.', max_length=20, unique=True, verbose_name='Subdivision-code')),
                ('naam', models.CharField(max_length=120, verbose_name='Naam')),
                ('korte_naam', models.CharField(blank=True, max_length=60, verbose_name='Korte naam')),
                ('uitleg', models.TextField(blank=True, help_text='Welke provincies/gebieden vallen eronder (redactioneel).', verbose_name='Uitleg / dekking')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Volgorde')),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regios', to='core.land', verbose_name='Land')),
            ],
            options={
                'verbose_name': 'Regio / deelstaat',
                'verbose_name_plural': "Regio's & deelstaten",
                'ordering': ['land', 'order', 'naam'],
            },
        ),
        migrations.CreateModel(
            name='Reisweek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jaar', models.PositiveSmallIntegerField(default=2026, verbose_name='Jaar')),
                ('weeknr', models.PositiveSmallIntegerField(verbose_name='Weeknummer')),
                ('start_label', models.CharField(help_text="bijv. '7 sep'.", max_length=20, verbose_name='Startdatum (weergave)')),
                ('drukte', models.PositiveSmallIntegerField(verbose_name='Drukte (0–100, hoog = druk)')),
                ('prijs', models.PositiveSmallIntegerField(verbose_name='Prijsindex (0–100, hoog = duur)')),
                ('weer', models.PositiveSmallIntegerField(verbose_name='Weer (0–100, hoog = mooi)')),
                ('overlap', models.PositiveSmallIntegerField(verbose_name='Overlap (0–100, hoog = veel landen vrij)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Volgorde')),
            ],
            options={
                'verbose_name': 'Reisweek',
                'verbose_name_plural': 'Reisweken (radar)',
                'ordering': ['jaar', 'weeknr'],
                'unique_together': {('jaar', 'weeknr')},
            },
        ),
        migrations.CreateModel(
            name='Feestdag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, help_text='GUID uit de API. Leeg bij handmatige rijen.', max_length=64, null=True, unique=True, verbose_name='OpenHolidays-ID')),
                ('naam', models.CharField(max_length=160, verbose_name='Naam')),
                ('categorie', models.CharField(choices=[('officieel', 'Officieel (vrije dag)'), ('officieus', 'Officieus / themadag')], default='officieel', max_length=12, verbose_name='Categorie')),
                ('start_datum', models.DateField(verbose_name='Datum')),
                ('eind_datum', models.DateField(blank=True, help_text='Alleen invullen als de dag meerdere dagen beslaat.', null=True, verbose_name='Einddatum')),
                ('type', models.CharField(blank=True, max_length=40, verbose_name='Type (API)')),
                ('landelijk', models.BooleanField(default=True, verbose_name='Landelijk')),
                ('emoji', models.CharField(blank=True, max_length=8, verbose_name='Emoji')),
                ('comment', models.CharField(blank=True, max_length=300, verbose_name='Toelichting')),
                ('bron', models.CharField(choices=[('api', 'OpenHolidays API'), ('handmatig', 'Handmatig')], default='api', max_length=12, verbose_name='Bron')),
                ('vergrendeld', models.BooleanField(default=False, verbose_name='Vergrendeld (import overslaan)')),
                ('imported_at', models.DateTimeField(blank=True, null=True, verbose_name='Laatst geïmporteerd')),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feestdagen', to='core.land', verbose_name='Land')),
                ('regios', models.ManyToManyField(blank=True, related_name='feestdagen', to='core.regio', verbose_name="Regio's")),
            ],
            options={
                'verbose_name': 'Feestdag',
                'verbose_name_plural': 'Feestdagen',
                'ordering': ['land', 'start_datum'],
                'indexes': [models.Index(fields=['land', 'categorie', 'start_datum'], name='core_feestd_land_id_5fea10_idx')],
            },
        ),
        migrations.CreateModel(
            name='Schoolvakantie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, help_text='GUID uit de API. Leeg bij handmatige rijen.', max_length=64, unique=True, verbose_name='OpenHolidays-ID')),
                ('naam', models.CharField(max_length=160, verbose_name='Naam')),
                ('type', models.CharField(blank=True, max_length=40, verbose_name='Type')),
                ('start_datum', models.DateField(verbose_name='Startdatum')),
                ('eind_datum', models.DateField(verbose_name='Einddatum')),
                ('landelijk', models.BooleanField(default=False, verbose_name="Landelijk (alle regio's)")),
                ('comment', models.CharField(blank=True, max_length=300, verbose_name='Toelichting (API)')),
                ('alias', models.CharField(blank=True, help_text="bijv. 'Krokus- / carnavalsvakantie'.", max_length=120, verbose_name='Alias')),
                ('status', models.CharField(blank=True, help_text="bijv. 'Wettelijk verplicht' of 'Adviesdata'.", max_length=80, verbose_name='Status')),
                ('note', models.CharField(blank=True, max_length=400, verbose_name='Redactionele noot')),
                ('bron', models.CharField(choices=[('api', 'OpenHolidays API'), ('handmatig', 'Handmatig')], default='api', max_length=12, verbose_name='Bron')),
                ('vergrendeld', models.BooleanField(default=False, help_text='Aan = handmatige correctie; de import laat deze rij met rust.', verbose_name='Vergrendeld (import overslaan)')),
                ('imported_at', models.DateTimeField(blank=True, null=True, verbose_name='Laatst geïmporteerd')),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schoolvakanties', to='core.land', verbose_name='Land')),
                ('regios', models.ManyToManyField(blank=True, related_name='schoolvakanties', to='core.regio', verbose_name="Regio's")),
            ],
            options={
                'verbose_name': 'Schoolvakantie',
                'verbose_name_plural': 'Schoolvakanties',
                'ordering': ['land', 'start_datum'],
                'indexes': [models.Index(fields=['land', 'start_datum'], name='core_school_land_id_7e7591_idx')],
            },
        ),
        migrations.CreateModel(
            name='WeerMaand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maand', models.PositiveSmallIntegerField(choices=[(1, 'jan'), (2, 'feb'), (3, 'mrt'), (4, 'apr'), (5, 'mei'), (6, 'jun'), (7, 'jul'), (8, 'aug'), (9, 'sep'), (10, 'okt'), (11, 'nov'), (12, 'dec')], verbose_name='Maand')),
                ('temp', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Temperatuur (°C)')),
                ('zon', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Zon (uren/dag)')),
                ('regen', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Regendagen')),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weermaanden', to='core.land', verbose_name='Land')),
            ],
            options={
                'verbose_name': 'Weer — maand',
                'verbose_name_plural': 'Weer (per maand)',
                'ordering': ['land', 'maand'],
                'unique_together': {('land', 'maand')},
            },
        ),
    ]
