# Generated by Django 5.1 on 2026-06-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_land_expert_credentials_expert_kort_expert_mono_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogartikel',
            name='body_html',
            field=models.TextField(blank=True, verbose_name='Inhoud (HTML)'),
        ),
        migrations.AddField(
            model_name='blogartikel',
            name='toc',
            field=models.JSONField(blank=True, default=list, verbose_name='Inhoudsopgave'),
        ),
    ]
