# Generated by Django 5.1 on 2026-06-22 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_blogartikel_body_html_blogartikel_toc'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogartikel',
            name='landen',
            field=models.ManyToManyField(blank=True, help_text="Toon dit artikel in het blogblok op deze landenpagina's.", related_name='blogartikelen', to='core.land', verbose_name='Gekoppelde landen'),
        ),
    ]
