# Generated by Django 5.1 on 2026-06-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_blogartikel_landen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feestdag',
            name='bron',
            field=models.CharField(choices=[('api', 'OpenHolidays API'), ('rijksoverheid', 'Rijksoverheid.nl (NL)'), ('edu-fr', 'Éducation nationale (FR)'), ('ferien-de', 'ferien-api.de (DE)'), ('nager', 'Nager.Date'), ('handmatig', 'Handmatig')], default='api', max_length=16, verbose_name='Bron'),
        ),
        migrations.AlterField(
            model_name='schoolvakantie',
            name='bron',
            field=models.CharField(choices=[('api', 'OpenHolidays API'), ('rijksoverheid', 'Rijksoverheid.nl (NL)'), ('edu-fr', 'Éducation nationale (FR)'), ('ferien-de', 'ferien-api.de (DE)'), ('nager', 'Nager.Date'), ('handmatig', 'Handmatig')], default='api', max_length=16, verbose_name='Bron'),
        ),
    ]
