# Generated by Django 5.1 on 2026-06-22 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_feestdag_bron_alter_schoolvakantie_bron'),
    ]

    operations = [
        migrations.CreateModel(
            name='Samenwerkingsaanvraag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=120, verbose_name='Naam')),
                ('bedrijf', models.CharField(blank=True, max_length=160, verbose_name='Bedrijf')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('soort', models.CharField(blank=True, max_length=80, verbose_name='Type samenwerking')),
                ('bericht', models.TextField(verbose_name='Bericht')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-adres')),
                ('verwerkt', models.BooleanField(default=False, verbose_name='Verwerkt')),
                ('aangemaakt', models.DateTimeField(auto_now_add=True, verbose_name='Ontvangen')),
            ],
            options={
                'verbose_name': 'Samenwerkingsaanvraag',
                'verbose_name_plural': 'Samenwerkingsaanvragen',
                'ordering': ['-aangemaakt'],
                'indexes': [models.Index(fields=['-aangemaakt'], name='core_samenw_aangema_b43ede_idx')],
            },
        ),
    ]
