# Generated by Django 5.1.15 on 2026-06-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_samenwerkingsaanvraag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectietekst',
            name='pagina',
            field=models.CharField(choices=[('home', 'Homepage'), ('over_ons', 'Over ons'), ('samenwerken', 'Samenwerken'), ('planner', 'Vakantieplanner'), ('druktekaart', 'Druktekaart')], max_length=40, verbose_name='Pagina'),
        ),
    ]
