# Generated by Django 5.1.15 on 2026-06-23 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_sectietekst_pagina'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogartikel',
            name='reviewer',
            field=models.ForeignKey(blank=True, help_text="Toont de 'Gecontroleerd door … · bijgewerkt' regel in de byline.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.expert', verbose_name='Gecontroleerd door'),
        ),
    ]
