# Generated by Django 5.1.15 on 2026-06-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_blogartikel_reviewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='body_html',
            field=models.TextField(blank=True, help_text="Hoofdtekst voor losse pagina's (privacy, cookies, voorwaarden). HTML toegestaan.", verbose_name='Inhoud (HTML)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='bedrijfsnaam',
            field=models.CharField(blank=True, default='', help_text="Rechtspersoon achter de site, bijv. 'Travel Nerds B.V.'.", max_length=160, verbose_name='Bedrijfsnaam (juridisch)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='vestigingsnummer',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Vestigingsnummer'),
        ),
    ]
