# Generated by Django 5.1.15 on 2026-06-24 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_land_gb_engeland'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(default='partner@travelnerds.nl', max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(blank=True, default='085 060 0043', max_length=40, verbose_name='Telefoon'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='show_phone',
            field=models.BooleanField(default=True, help_text='Uit = nergens een telefoonnummer tonen.', verbose_name='Telefoonnummer tonen'),
        ),
    ]
