# Generated by Django 5.1.15 on 2026-06-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_sitesettings_contact_travelnerds'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogartikel',
            name='gepubliceerd_op',
            field=models.DateTimeField(blank=True, help_text='Echte publicatiedatum (voor de Google News-sitemap). Leeg = niet in news-sitemap.', null=True, verbose_name='Gepubliceerd op'),
        ),
    ]
