# Generated by Django 5.1.15 on 2026-06-24 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_backfill_blog_gepubliceerd_op'),
    ]

    operations = [
        migrations.CreateModel(
            name='NlPlaats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=120, unique=True, verbose_name='Plaats / gemeente')),
                ('regio', models.CharField(choices=[('Noord', 'Noord'), ('Midden', 'Midden'), ('Zuid', 'Zuid')], max_length=10, verbose_name='Regio')),
            ],
            options={
                'verbose_name': 'NL plaats → regio',
                'verbose_name_plural': 'NL plaatsen → regio',
                'ordering': ['naam'],
            },
        ),
    ]
