# Generated by Django 5.1.15 on 2026-06-24 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_nlplaats'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plaats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=120, verbose_name='Plaats / gemeente')),
                ('regio', models.CharField(help_text='Naam van de Regio waar deze plaats onder valt.', max_length=120, verbose_name='Regio')),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plaatsen', to='core.land')),
            ],
            options={
                'verbose_name': 'plaats → regio',
                'verbose_name_plural': 'plaatsen → regio',
                'ordering': ['land', 'naam'],
                'unique_together': {('land', 'naam')},
            },
        ),
        migrations.DeleteModel(
            name='NlPlaats',
        ),
    ]
