# Generated by Django 5.1.15 on 2026-06-25 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_plaats_delete_nlplaats'),
    ]

    operations = [
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_key', models.CharField(db_index=True, max_length=24, unique=True, verbose_name='Site-key')),
                ('domein', models.CharField(help_text='Zonder protocol, bv. example.com.', max_length=190, verbose_name='Domein')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail (waarschuwingen)')),
                ('actief', models.BooleanField(default=True, verbose_name='Actief')),
                ('aangemaakt', models.DateTimeField(auto_now_add=True, verbose_name='Aangemaakt')),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='core.land', verbose_name='Land')),
            ],
            options={
                'verbose_name': 'Widget',
                'verbose_name_plural': 'Widgets',
                'ordering': ['-aangemaakt'],
            },
        ),
        migrations.CreateModel(
            name='WidgetPagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500, verbose_name='Pagina-URL')),
                ('status', models.CharField(choices=[('pending', 'In afwachting'), ('actief', 'Actief'), ('teaser', 'Teaser')], default='pending', max_length=10, verbose_name='Status')),
                ('backlink_ok', models.BooleanField(default=False, verbose_name='Backlink gevonden')),
                ('fail_count', models.PositiveSmallIntegerField(default=0, verbose_name='Mislukte checks op rij')),
                ('laatst_gecheckt', models.DateTimeField(blank=True, null=True, verbose_name='Laatst gecheckt')),
                ('laatst_ok', models.DateTimeField(blank=True, null=True, verbose_name='Laatst backlink gezien')),
                ('grace_mail_op', models.DateTimeField(blank=True, null=True, verbose_name='Waarschuwingsmail verstuurd')),
                ('aangemaakt', models.DateTimeField(auto_now_add=True, verbose_name='Aangemaakt')),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paginas', to='core.widget')),
            ],
            options={
                'verbose_name': 'Widget-pagina',
                'verbose_name_plural': "Widget-pagina's",
                'ordering': ['-aangemaakt'],
                'unique_together': {('widget', 'url')},
            },
        ),
    ]
