# Generated by Django 5.1.15 on 2026-06-26 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_sitesettings_klantenservice_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(default='klantenservice@travelnerds.nl', max_length=254, verbose_name='E-mail'),
        ),
    ]
