# Generated by Django 5.1.15 on 2026-06-26 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_sitesettings_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kennisbankartikel',
            options={'ordering': ['order', 'titel'], 'verbose_name': 'Kennisbank-artikel', 'verbose_name_plural': 'Kennisbank-artikelen'},
        ),
        migrations.AddField(
            model_name='kennisbankartikel',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kb_artikelen', to='core.expert', verbose_name='Auteur'),
        ),
        migrations.AddField(
            model_name='kennisbankartikel',
            name='body_html',
            field=models.TextField(blank=True, verbose_name='Inhoud (HTML)'),
        ),
        migrations.AddField(
            model_name='kennisbankartikel',
            name='briefing',
            field=models.TextField(blank=True, help_text='Brief + invalshoek + zoekintentie + aanbevolen interne links.', verbose_name='Redactie-briefing'),
        ),
        migrations.AddField(
            model_name='kennisbankartikel',
            name='bron_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Bron-URL'),
        ),
        migrations.AddField(
            model_name='kennisbankartikel',
            name='commerciele_waarde',
            field=models.CharField(blank=True, max_length=10, verbose_name='Commerciële waarde'),
        ),
        migrations.AddField(
            model_name='kennisbankartikel',
            name='gepubliceerd_op',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Gepubliceerd op'),
        ),
        migrations.AddField(
            model_name='kennisbankartikel',
            name='kb_id',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Backlog-ID'),
        ),
        migrations.AddField(
            model_name='kennisbankartikel',
            name='land',
            field=models.ForeignKey(blank=True, help_text='Leeg = Europa-breed / niet landgebonden.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kennisbank', to='core.land', verbose_name='Land'),
        ),
        migrations.AddField(
            model_name='kennisbankartikel',
            name='prioriteit',
            field=models.CharField(blank=True, max_length=4, verbose_name='Prioriteit'),
        ),
        migrations.AddField(
            model_name='kennisbankartikel',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kb_reviews', to='core.expert', verbose_name='Reviewer'),
        ),
        migrations.AddField(
            model_name='kennisbankartikel',
            name='seo_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='SEO-titel'),
        ),
        migrations.AddField(
            model_name='kennisbankartikel',
            name='status',
            field=models.CharField(choices=[('concept', 'Concept'), ('te_reviewen', 'Te reviewen'), ('gepubliceerd', 'Gepubliceerd')], default='concept', max_length=14, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='kennisbankartikel',
            name='toc',
            field=models.JSONField(blank=True, default=list, verbose_name='Inhoudsopgave'),
        ),
        migrations.AlterField(
            model_name='kennisbankartikel',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Actief (publiek zichtbaar)'),
        ),
        migrations.AlterField(
            model_name='kennisbankartikel',
            name='categorie',
            field=models.CharField(blank=True, max_length=80, verbose_name='Categorie (cluster)'),
        ),
    ]
