// landdata.js — volledige schoolvakantie- & feestdagdata 2026 voor NL en DE.
// Bronnen: Rijksoverheid / kalenderapp.nl (NL), Kultusministerkonferenz / kalenderpedia.de / ADAC (DE).
// Adviesdata (NL voorjaar/herfst) en "ohne Gewähr" (DE) — scholen mogen afwijken.

window.LANDDATA = {
  nl: {
    code: "nl",
    name: "Nederland",
    flag: "🇳🇱",
    jaar: 2026,
    intro: "Nederland kent vijf schoolvakanties per jaar, gespreid over drie regio's — Noord, Midden en Zuid — om de drukte op de wegen en in vakantiegebieden te verdelen. De meivakantie, zomervakantie en kerstvakantie staan wettelijk vast; de voorjaars- en herfstvakantie zijn adviesdata waar scholen van mogen afwijken.",
    regios: ["Noord", "Midden", "Zuid"],
    regioUitleg: {
      Noord: "Groningen, Friesland, Drenthe, Overijssel, Noord-Holland, grootste deel Flevoland",
      Midden: "Zuid-Holland, Utrecht en een deel van Gelderland",
      Zuid: "Zeeland, Limburg, Noord-Brabant en een deel van Gelderland",
    },
    // vakanties: per periode de data per regio + status (verplicht/advies)
    vakanties: [
      {
        naam: "Voorjaarsvakantie", alias: "Krokus- / carnavalsvakantie", status: "Adviesdata",
        maand: "februari",
        perRegio: { Noord: "21 feb – 1 mrt", Midden: "14 – 22 feb", Zuid: "14 – 22 feb" },
        weken:   { Noord: "wk 8–9", Midden: "wk 7–8", Zuid: "wk 7–8" },
        note: "Valt samen met carnaval (15–17 feb). In het zuiden vaak carnavalsvakantie genoemd.",
      },
      {
        naam: "Meivakantie", alias: "", status: "Verplicht (1 wk) · advies 2e wk",
        maand: "april–mei",
        perRegio: { Noord: "25 apr – 3 mei", Midden: "25 apr – 3 mei", Zuid: "25 apr – 3 mei" },
        weken:   { Noord: "wk 17–18", Midden: "wk 17–18", Zuid: "wk 17–18" },
        note: "Veel scholen breiden uit met een extra week (advies OCW: 18–26 april).",
      },
      {
        naam: "Zomervakantie", alias: "", status: "Wettelijk verplicht",
        maand: "juli–augustus",
        perRegio: { Noord: "18 jul – 30 aug", Midden: "11 jul – 23 aug", Zuid: "4 jul – 16 aug" },
        weken:   { Noord: "wk 29–35", Midden: "wk 28–34", Zuid: "wk 27–33" },
        note: "Zes weken, gespreid over de drie regio's. Regio Nijmegen wijkt soms af i.v.m. de Vierdaagse.",
      },
      {
        naam: "Herfstvakantie", alias: "", status: "Adviesdata",
        maand: "oktober",
        perRegio: { Noord: "17 – 25 okt", Midden: "10 – 18 okt", Zuid: "10 – 18 okt" },
        weken:   { Noord: "wk 42–43", Midden: "wk 41–42", Zuid: "wk 41–42" },
        note: "Eén week. Regio Noord een week later dan Midden en Zuid.",
      },
      {
        naam: "Kerstvakantie", alias: "", status: "Wettelijk verplicht",
        maand: "december–januari",
        perRegio: { Noord: "19 dec – 3 jan ’27", Midden: "19 dec – 3 jan ’27", Zuid: "19 dec – 3 jan ’27" },
        weken:   { Noord: "wk 51–53", Midden: "wk 51–53", Zuid: "wk 51–53" },
        note: "Twee weken rond Kerst en Nieuwjaar, voor heel Nederland gelijk.",
      },
    ],
    // officiële feestdagen (vrije dagen)
    feestdagen: [
      { naam: "Nieuwjaarsdag", datum: "1 januari", dag: "do" },
      { naam: "Goede Vrijdag", datum: "3 april", dag: "vr" },
      { naam: "Eerste Paasdag", datum: "5 april", dag: "zo" },
      { naam: "Tweede Paasdag", datum: "6 april", dag: "ma" },
      { naam: "Koningsdag", datum: "27 april", dag: "ma" },
      { naam: "Bevrijdingsdag", datum: "5 mei", dag: "di", note: "Officieel vrij meestal eens per 5 jaar" },
      { naam: "Hemelvaartsdag", datum: "14 mei", dag: "do" },
      { naam: "Eerste Pinksterdag", datum: "24 mei", dag: "zo" },
      { naam: "Tweede Pinksterdag", datum: "25 mei", dag: "ma" },
      { naam: "Eerste Kerstdag", datum: "25 december", dag: "vr" },
      { naam: "Tweede Kerstdag", datum: "26 december", dag: "za" },
    ],
    // officiële vrije schooldagen (studiedagen / margedagen)
    studiedagen: {
      uitleg: "Naast de landelijke vakanties plannen scholen zelf studiedagen (margedagen): roostervrije dagen voor leerlingen waarop het team werkt. Deze verschillen per school en staan in de schoolgids.",
      voorbeelden: [
        "Vaak een vrijdag vóór een vakantie",
        "Dag na Koningsdag of rond Bevrijdingsdag",
        "Eerste of laatste dag voor de zomervakantie",
        "Gemiddeld 4–7 studiedagen per schooljaar",
      ],
    },
    // officieuze feestdagen
    officieus: [
      { naam: "Valentijnsdag", datum: "14 feb", emoji: "💌" },
      { naam: "Carnaval", datum: "15–17 feb", emoji: "🎭" },
      { naam: "Moederdag", datum: "10 mei", emoji: "💐" },
      { naam: "Vaderdag", datum: "21 jun", emoji: "👔" },
      { naam: "Dierendag", datum: "4 okt", emoji: "🐾" },
      { naam: "Halloween", datum: "31 okt", emoji: "🎃" },
      { naam: "Sint-Maarten", datum: "11 nov", emoji: "🏮" },
      { naam: "Sinterklaas", datum: "5 dec", emoji: "🎁" },
      { naam: "Oudjaarsdag", datum: "31 dec", emoji: "🎆" },
    ],
    faq: [
      { v: "Mag mijn school afwijken van deze vakantiedata?", a: "De meivakantie, zomervakantie en kerstvakantie zijn wettelijk verplicht — daar mag geen enkele school van afwijken. De voorjaars- en herfstvakantie zijn adviesdata: scholen mogen hier, met instemming van de medezeggenschapsraad, van afwijken. Check altijd de schoolgids voor de definitieve data." },
      { v: "Waarom zijn de vakanties verdeeld over drie regio's?", a: "De spreiding over Noord, Midden en Zuid is in de jaren '80 ingevoerd om de drukte op de wegen en in vakantiegebieden te verminderen. Vooral de zomervakantie is daardoor regionaal verschillend; de andere vakanties volgen meestal het landelijke advies." },
      { v: "Wat is het verschil tussen de krokus- en carnavalsvakantie?", a: "Dat is dezelfde voorjaarsvakantie. In het zuiden van het land valt deze vaak rond carnaval en wordt hij carnavalsvakantie genoemd; elders heet hij krokusvakantie. In 2026 vallen de adviesdata en carnaval grotendeels samen." },
      { v: "Wanneer is het het rustigst om met de kinderen weg te gaan?", a: "Net buiten de piek. Begin juli (als alleen regio Zuid net vrij is) en eind augustus tot half september zijn duidelijk rustiger en goedkoper dan de drukke weken eind juli en begin augustus, wanneer alle regio's én veel buurlanden tegelijk vrij zijn." },
      { v: "Mag ik buiten de schoolvakanties op vakantie?", a: "Alleen in uitzonderlijke gevallen en met toestemming van de school. Zomaar eerder vertrekken valt onder ongeoorloofd schoolverzuim en kan een boete opleveren. Plan dus binnen de vakanties — of kies een slimme, rustige week erbinnen." },
    ],
    bron: "Bron: Rijksoverheid (ministerie van OCW). Verplichte data staan vast; adviesdata kunnen per school verschillen — raadpleeg de schoolgids.",
    bijgewerkt: "mei 2026",
    weer: {
      bron: "Langjarig gemiddelde · KNMI (De Bilt)",
      beste: "Mei, juni en september: zacht, relatief droog en buiten de drukste weken.",
      maanden: [
        { m: "jan", temp: 6,  zon: 2,   regen: 12 },
        { m: "feb", temp: 7,  zon: 3,   regen: 10 },
        { m: "mrt", temp: 10, zon: 4,   regen: 11 },
        { m: "apr", temp: 14, zon: 6,   regen: 9 },
        { m: "mei", temp: 18, zon: 7,   regen: 9 },
        { m: "jun", temp: 21, zon: 7,   regen: 9 },
        { m: "jul", temp: 23, zon: 7,   regen: 9 },
        { m: "aug", temp: 23, zon: 6,   regen: 9 },
        { m: "sep", temp: 19, zon: 5,   regen: 10 },
        { m: "okt", temp: 15, zon: 4,   regen: 11 },
        { m: "nov", temp: 10, zon: 2,   regen: 13 },
        { m: "dec", temp: 7,  zon: 1.5, regen: 13 },
      ],
    },
  },

  de: {
    code: "de",
    name: "Duitsland",
    flag: "🇩🇪",
    jaar: 2026,
    intro: "Duitsland heeft geen landelijke schoolvakanties: elk van de 16 deelstaten (Bundesländer) bepaalt zijn eigen data. Alleen de zomervakantie wordt door de Kultusministerkonferenz gespreid (het 'Ferienkorridor') om files te voorkomen. Daardoor is het hele land vrijwel nooit tegelijk vrij — handig om te weten bij het plannen van een rustige reis.",
    regios: [
      "Baden-Württemberg", "Bayern", "Berlin", "Brandenburg", "Bremen", "Hamburg",
      "Hessen", "Meckl.-Vorp.", "Niedersachsen", "NRW", "Rheinland-Pfalz", "Saarland",
      "Sachsen", "Sachsen-Anhalt", "Schleswig-Holstein", "Thüringen",
    ],
    // per vakantieperiode: data per deelstaat (kort). "—" = geen / valt buiten 2026.
    vakanties: [
      {
        naam: "Winterferien", alias: "Februari", status: "Per deelstaat", maand: "jan–feb",
        perRegio: {
          "Baden-Württemberg": "verschilt per school", "Bayern": "16–20 feb", "Berlin": "2–7 feb",
          "Brandenburg": "2–7 feb", "Bremen": "2–3 feb", "Hamburg": "30 jan", "Hessen": "—",
          "Meckl.-Vorp.": "9–20 feb", "Niedersachsen": "2–3 feb", "NRW": "—", "Rheinland-Pfalz": "—",
          "Saarland": "16–20 feb", "Sachsen": "9–21 feb", "Sachsen-Anhalt": "31 jan – 6 feb",
          "Schleswig-Holstein": "—", "Thüringen": "16–21 feb",
        },
        note: "Niet elke deelstaat heeft winter-/faschingsferien.",
      },
      {
        naam: "Osterferien", alias: "Pasen", status: "Per deelstaat", maand: "maart–april",
        perRegio: {
          "Baden-Württemberg": "30 mrt – 11 apr", "Bayern": "30 mrt – 10 apr", "Berlin": "30 mrt – 10 apr",
          "Brandenburg": "30 mrt – 10 apr", "Bremen": "23 mrt – 7 apr", "Hamburg": "2 – 13 mrt",
          "Hessen": "30 mrt – 10 apr", "Meckl.-Vorp.": "30 mrt – 8 apr", "Niedersachsen": "23 mrt – 7 apr",
          "NRW": "30 mrt – 11 apr", "Rheinland-Pfalz": "30 mrt – 10 apr", "Saarland": "7 – 17 apr",
          "Sachsen": "3 – 10 apr", "Sachsen-Anhalt": "30 mrt – 4 apr", "Schleswig-Holstein": "26 mrt – 10 apr",
          "Thüringen": "7 – 17 apr",
        },
      },
      {
        naam: "Pfingstferien", alias: "Pinksteren", status: "Per deelstaat", maand: "mei–juni",
        perRegio: {
          "Baden-Württemberg": "26 mei – 5 jun", "Bayern": "26 mei – 5 jun", "Berlin": "15 / 26 mei",
          "Brandenburg": "15 / 26 mei", "Bremen": "15 / 26 mei", "Hamburg": "11 – 15 mei",
          "Hessen": "—", "Meckl.-Vorp.": "15 / 22–26 mei", "Niedersachsen": "15 / 26 mei",
          "NRW": "26 mei", "Rheinland-Pfalz": "—", "Saarland": "—", "Sachsen": "15 mei",
          "Sachsen-Anhalt": "26 – 29 mei", "Schleswig-Holstein": "15 mei", "Thüringen": "15 mei",
        },
        note: "Vaak losse brugdagen rond Pinksteren; Beieren & Baden-Württemberg hebben twee volle weken.",
      },
      {
        naam: "Sommerferien", alias: "Zomer", status: "Gespreid (KMK)", maand: "juni–september",
        perRegio: {
          "Baden-Württemberg": "30 jul – 12 sep", "Bayern": "3 aug – 14 sep", "Berlin": "9 jul – 22 aug",
          "Brandenburg": "9 jul – 22 aug", "Bremen": "2 jul – 12 aug", "Hamburg": "9 jul – 19 aug",
          "Hessen": "29 jun – 7 aug", "Meckl.-Vorp.": "13 jul – 22 aug", "Niedersachsen": "2 jul – 12 aug",
          "NRW": "20 jul – 1 sep", "Rheinland-Pfalz": "29 jun – 7 aug", "Saarland": "29 jun – 7 aug",
          "Sachsen": "4 jul – 14 aug", "Sachsen-Anhalt": "4 jul – 14 aug", "Schleswig-Holstein": "4 jul – 15 aug",
          "Thüringen": "4 jul – 14 aug",
        },
        note: "Eerste start: Hessen/RP/Saarland (29 jun). Laatste: Beieren (t/m 14 sep). Rond 3–5 aug heeft héél Duitsland tegelijk vrij — landelijk verkeershoogtepunt.",
      },
      {
        naam: "Herbstferien", alias: "Herfst", status: "Per deelstaat", maand: "oktober–november",
        perRegio: {
          "Baden-Württemberg": "26 – 31 okt", "Bayern": "2 – 6 / 18 nov", "Berlin": "19 – 31 okt",
          "Brandenburg": "19 – 30 okt", "Bremen": "12 – 24 okt", "Hamburg": "19 – 30 okt",
          "Hessen": "5 – 17 okt", "Meckl.-Vorp.": "15 – 24 okt", "Niedersachsen": "12 – 24 okt",
          "NRW": "17 – 31 okt", "Rheinland-Pfalz": "5 – 16 okt", "Saarland": "5 – 16 okt",
          "Sachsen": "12 – 24 okt", "Sachsen-Anhalt": "19 – 30 okt", "Schleswig-Holstein": "12 – 24 okt",
          "Thüringen": "12 – 24 okt",
        },
      },
      {
        naam: "Weihnachtsferien", alias: "Kerst", status: "Per deelstaat", maand: "december–januari",
        perRegio: {
          "Baden-Württemberg": "23 dec – 9 jan", "Bayern": "24 dec – 8 jan", "Berlin": "23 dec – 2 jan",
          "Brandenburg": "23 dec – 2 jan", "Bremen": "23 dec – 9 jan", "Hamburg": "21 dec – 1 jan",
          "Hessen": "23 dec – 12 jan", "Meckl.-Vorp.": "21 dec – 2 jan", "Niedersachsen": "23 dec – 9 jan",
          "NRW": "23 dec – 6 jan", "Rheinland-Pfalz": "23 dec – 8 jan", "Saarland": "21 – 31 dec",
          "Sachsen": "23 dec – 2 jan", "Sachsen-Anhalt": "21 dec – 2 jan", "Schleswig-Holstein": "21 dec – 6 jan",
          "Thüringen": "23 dec – 2 jan",
        },
      },
    ],
    feestdagen: [
      { naam: "Neujahr", datum: "1 januari", dag: "do" },
      { naam: "Karfreitag", datum: "3 april", dag: "vr" },
      { naam: "Ostermontag", datum: "6 april", dag: "ma" },
      { naam: "Tag der Arbeit", datum: "1 mei", dag: "vr" },
      { naam: "Christi Himmelfahrt", datum: "14 mei", dag: "do" },
      { naam: "Pfingstmontag", datum: "25 mei", dag: "ma" },
      { naam: "Tag der Deutschen Einheit", datum: "3 oktober", dag: "za" },
      { naam: "1. Weihnachtstag", datum: "25 december", dag: "vr" },
      { naam: "2. Weihnachtstag", datum: "26 december", dag: "za" },
    ],
    feestdagenNote: "Bovenstaande gelden in heel Duitsland. Regionaal komen erbij: Heilige Drei Könige (6 jan · BW, BY, ST), Fronleichnam (4 jun · kath. deelstaten), Mariä Himmelfahrt (15 aug · BY deels, SL), Reformationstag (31 okt · noord/oost), Allerheiligen (1 nov · kath.) en Buß- und Bettag (18 nov · Sachsen).",
    studiedagen: {
      uitleg: "Deelstaten geven scholen 'bewegliche Ferientage': losse roostervrije dagen die de school zelf inplant — vaak brugdagen of rond Fasching/Karneval. Maximaal 6 per schooljaar, verschilt per school.",
      voorbeelden: [
        "Rosenmontag & Faschingsdienstag (16–17 feb)",
        "Brugdag na Christi Himmelfahrt (15 mei)",
        "Brugdag rond Fronleichnam (kath. deelstaten)",
        "Reformationstag in deelstaten zonder vrije dag",
      ],
    },
    officieus: [
      { naam: "Valentinstag", datum: "14 feb", emoji: "❤️" },
      { naam: "Rosenmontag", datum: "16 feb", emoji: "🎭" },
      { naam: "Muttertag", datum: "10 mei", emoji: "💐" },
      { naam: "Vatertag", datum: "14 mei", emoji: "👔" },
      { naam: "Halloween", datum: "31 okt", emoji: "🎃" },
      { naam: "Oktoberfest", datum: "19 sep – 4 okt", emoji: "🍺" },
      { naam: "Nikolaus", datum: "6 dec", emoji: "🎅" },
      { naam: "Silvester", datum: "31 dec", emoji: "🎆" },
    ],
    regioInfo: "Duitsland kent geen provincie-indeling zoals Nederland: elk van de 16 deelstaten plant zelf. Alleen de zomervakantie wordt centraal gespreid in een 'Ferienkorridor' van eind juni tot half september. Voor Nederlandse reizigers zijn vooral de buur-deelstaten Niedersachsen en Nordrhein-Westfalen relevant — die grenzen direct aan ons land en hun vakanties overlappen het sterkst met de onze.",
    faq: [
      { v: "Waarom heeft Duitsland 16 verschillende schoolvakanties?", a: "Elke deelstaat (Bundesland) bepaalt zijn eigen vakantiedata. Alleen de zomervakantie wordt door de Kultusministerkonferenz gecoördineerd en gespreid, zodat niet heel Duitsland tegelijk de weg op gaat. Daardoor verschilt het per deelstaat sterk wanneer de scholen dicht zijn." },
      { v: "Welke deelstaten grenzen aan Nederland?", a: "Niedersachsen (Nedersaksen) en Nordrhein-Westfalen (NRW) grenzen direct aan Nederland. NRW is met ruim 18 miljoen inwoners de dichtstbevolkte deelstaat — als die vakantie heeft, merk je dat aan de drukte op de Duitse snelwegen en in de grensstreek." },
      { v: "Wanneer heeft heel Duitsland tegelijk vakantie?", a: "Rond 3 tot 5 augustus 2026 overlappen voor het eerst alle 16 deelstaten: dan is het in heel Duitsland zomervakantie. Dat is een landelijk verkeershoogtepunt — vermijd reizen op die vrijdag en zaterdag als je files wilt ontlopen." },
      { v: "Wat zijn 'bewegliche Ferientage'?", a: "Dat zijn losse, roostervrije dagen die scholen zelf mogen inplannen — maximaal zes per schooljaar. Vaak worden ze gebruikt voor brugdagen of voor Fasching/Karneval (Rosenmontag). Ze verschillen per school en staan niet in de landelijke kalender." },
      { v: "Hoe vermijd ik de drukte in Duitsland?", a: "Reis in een week waarin de grote, dichtbevolkte deelstaten (NRW, Beieren, Baden-Württemberg) nog naar school gaan, of juist net voor of na hun vakantie. Begin juli en half september zijn vaak het rustigst en voordeligst." },
    ],
    bron: "Bron: Kultusministerkonferenz (KMK) en de afzonderlijke deelstaten. Alle data onder voorbehoud (ohne Gewähr); afzonderlijke scholen kunnen afwijken.",
    bijgewerkt: "mei 2026",
    weer: {
      bron: "Langjarig gemiddelde · Deutscher Wetterdienst (landelijk)",
      beste: "Mei tot september voor zon; juli en augustus het warmst, maar ook het drukst en duurst.",
      maanden: [
        { m: "jan", temp: 4,  zon: 2, regen: 11 },
        { m: "feb", temp: 5,  zon: 3, regen: 9 },
        { m: "mrt", temp: 10, zon: 4, regen: 10 },
        { m: "apr", temp: 14, zon: 6, regen: 9 },
        { m: "mei", temp: 19, zon: 7, regen: 11 },
        { m: "jun", temp: 22, zon: 8, regen: 11 },
        { m: "jul", temp: 24, zon: 8, regen: 11 },
        { m: "aug", temp: 24, zon: 7, regen: 10 },
        { m: "sep", temp: 19, zon: 5, regen: 9 },
        { m: "okt", temp: 14, zon: 4, regen: 9 },
        { m: "nov", temp: 8,  zon: 2, regen: 10 },
        { m: "dec", temp: 5,  zon: 2, regen: 11 },
      ],
    },
  },
};
